AY2425S2-CS2103T-T08-4/tp

docs/AboutUs.md

Add my image to AboutUs.md and updated portfolio
Closes #19

docs: Update AboutUs.md

---

docs/AboutUs.md

feat: Update AboutUs.md to include Advay's information

---

docs/DeveloperGuide.md

Closes #26 
-  Please give credit to this PR to @Timothy-Ho0203

docs: Add initial version of dev guide

---

README.md

- Added links to our resources (User Guide, Dev Guide, Github Issues)
- Added nice emojis and a cool product pitch for our app TalentMatch
- Closes #10

chore: Update README.md to TalentMatch

---

README.md

Branch fix readme ci

---

.gitignore
.vscode/settings.json
build.gradle
docs/DeveloperGuide.md
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/util/IconUtil.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/ui/util/IconUtilTest.java

- Added icons to our UI
-  Changed tags to specializations
- Added tests for icon generation
- Added some dependencies for testing and fontAwesome icons
Closes #47

feat: Add skills and corresponding UI for TalentMatch

---

.codecov.yml
docs/DeveloperGuide.md
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/util/IconUtil.java
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/ui/util/IconUtilTest.java

chore: Update DG and add AI reference

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/DeleteJobCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

DeleteJobCommand temporarily takes in prefixes to delete the job rather than index, will fix after we have Job View
Fixes #54

feat: Add AddJobCommand

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/application/ApplicationStatus.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PersonListPanel.java
src/main/java/seedu/address/ui/UiManager.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml
src/test/java/seedu/address/logic/commands/AddCommandTest.java

- Render Applications into TalentMatch
- Add wrapper APIs to ModelManager for getApplicationByJob
- Add wrapper APIs to ModelManager for getApplicationByPerson

feat: Add person view

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
src/main/java/seedu/address/logic/commands/EditJobCommand.java
src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteJobCommandParser.java
src/main/java/seedu/address/logic/parser/EditJobCommandParser.java
src/main/java/seedu/address/model/job/Job.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteJobCommandTest.java
src/test/java/seedu/address/testutil/JobBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

- Add EditJobCommand
- Fix Prefix identification bug with AddCommandParser
- Refactor DeleteJobCommand to delete by Index instead of by Job
- Add JobBuilder for future tests
- Add tests for DeleteJobCommand
Fixes #82

feat: Add EditJobCommand 

---

docs/UserGuide.md

docs: Update UG

---

src/main/java/seedu/address/model/application/ApplicationStatusPredicate.java
src/main/java/seedu/address/ui/MainWindow.java

feat: Make job view the primary view, and add ApplicationStatusPredicate

---

src/main/java/seedu/address/model/DoublyLinkedList.java

feat: Modify internal representation of command DLL to use java collections

---

src/main/java/seedu/address/logic/commands/AddApplicationCommand.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/commands/AdvanceApplicationCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteApplicationCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/EditJobCommand.java
src/main/java/seedu/address/logic/commands/FindAppCommand.java
src/main/java/seedu/address/logic/commands/ViewJobCommand.java
src/test/java/seedu/address/logic/LogicManagerTest.java

- Changed delete to del for person and job command
- change advapp to adv
Fixes #129

fix: Standardise command box instructions

---

src/main/java/seedu/address/MainApp.java

Implements a fix by ensuring loading logic accounts for the dependency between address book storage and applications manager storage.
Closes #147

Fix storage bugs

---

src/main/java/seedu/address/logic/commands/EditJobCommand.java
src/main/java/seedu/address/model/job/UniqueJobList.java

Fix editjob

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/FindAppCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindJobCommand.java
src/main/java/seedu/address/logic/commands/SwitchViewCommand.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java

Add more descriptive messages for when find returns no results

---

src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Degree.java
src/main/java/seedu/address/model/person/Email.java
src/main/java/seedu/address/model/person/Phone.java
src/main/java/seedu/address/model/person/School.java
src/main/java/seedu/address/ui/HelpWindow.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/EmailTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Fix job parsers

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
src/main/java/seedu/address/logic/parser/AdvanceApplicationCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteApplicationCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteJobCommandParser.java
src/main/java/seedu/address/logic/parser/FindAppCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ViewPersonCommandParser.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java

- Reduce code duplication
- Close #135

Various hotfixes

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/commands/AdvanceApplicationCommand.java
src/main/java/seedu/address/logic/commands/DeleteApplicationCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/EditJobCommand.java
src/main/java/seedu/address/logic/commands/FindAppCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindJobCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/ListJobCommand.java
src/main/java/seedu/address/logic/commands/ViewJobCommand.java
src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
src/main/java/seedu/address/model/job/JobRounds.java
src/main/java/seedu/address/model/job/JobTitle.java
src/test/java/seedu/address/logic/commands/FindAppCommandTest.java

Refactor error message for incorrect view into Messages.java
Fix punctuation in error messages

refactor: Refactor error messages

---

src/main/java/seedu/address/ui/JobSpecificStatsPanel.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PersonDetailPanel.java

- spacing added
- wrap added
- bar chart has applied

fix: Fix css
